# Generated by Django 4.1.7 on 2023-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP_Address", models.CharField(max_length=1024)),
                ("UserName", models.CharField(max_length=1024)),
                ("CPU_model", models.CharField(max_length=1024)),
                ("Memory_info", models.CharField(max_length=1024)),
                ("System_info", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
